# Worlds to enable the plugin in
enabled-worlds:
  - world
# If this is true, the plugin will work in all worlds EXCEPT for those in "enabled-worlds"
enabled-to-disabled: false

# If this is true, the plugin will prevent eating during disabled ranges
prevent-eating: true
# If this is true, the plugin will prevent drinking during disabled ranges
prevent-drinking: true

# World time ranges to disable eating/drinking
# Times are in ticks from 0 to 24000
# Two ranges are needed if the time range goes over sunrise
disabled-world-times:
  - '13000-23000'

# Server time ranges to disable eating/drinking
# Times are in hours:minutes from 00:00 to 24:00
# Two ranges are needed if the time range goes over midnight
disabled-server-times:
# - '21:00-24:00'
# - '00:00-6:00'

# Message to send to the player if they are in a disabled range
# If this is an empty string (''), the player won't be sent anything
disabled-message: '&cYou cannot eat/drink during this time!'

# This will prevent starvation damage while a player is fasting
prevent-starvation-damage: true

# This will prevent players from going below 3 hunger bars while fasting
# (if they were at or above 3 before fasting)
prevent-sprint-loss: true