name: Fasting
main: com.darkender.plugins.fasting.Fasting
version: ${project.version}
api-version: 1.15
author: Techdoodle
commands:
  fasting:
    aliases:
      - fast
    usage: "Usage: /fasting [check|reload]"
    description: "The core Fasting command"
    permission: fasting.cmd
permissions:
  fasting.cmd:
    description: "Permission for the core Fasting command"
  fasting.cmd.check:
    description: "Permission to check if a player can eat/drink"
    default: true
  fasting.cmd.reload:
    description: "Permission to reload the config"
  fasting.cmd.*:
    children:
      fasting.cmd.check: true
      fasting.cmd.reload: true